project:
  type: website

website:
  title: "Coffee, Curiosity, and Chatbots!"
  navbar:
    right:
      - about.qmd
      - icon: instagram
        href: https://www.instagram.com/_kaitlynhu/
format:
  html:
    theme: litera
    css: styles.css

execute:
  freeze: auto


